### ISSUE TITLE
Auth per connection

### ISSUE THREAD

**Issue by mtharrison** [nearform/anger#10]
It would be cool if we could specify different auth options per connection. What do you think about making the `auth` option optionally take a function that takes the client index and a `sender` boolean?

```js
const instance = anger({
  ...
  auth: (i, sender) => {
  
    return { headers: { ... } }
  },
  ...
})
```

**Comment by mcollina** [comment]
👍 ,

I'll just do `auth: (sender, i) => `, just because it fits with `forEach`.
