### ISSUE TITLE
no batching

### ISSUE THREAD

**Issue by mcollina** [nearform/anger#4]
Currently a batch of messages are triggered, and then the tester wait fot all to complete. This is extremely stressful for an application.
I think a more realistic test is to send all the messages are the beginning, but then trigger a new one once the previous one has completed. In this way we can reproduce a more stable load, rather than a series of spikes.

**Comment by davidmarkclements** [comment]
yes - as an addition it would be nice if you specify requests concurrency too

currently concurrency === request count (e.g. all 1000 at once)

you're saying concurrency =1

but it would be cool to also say, concurrency = 3  - so you split request count into three queues, and then serially trigger as described
