### ISSUE TITLE
Export all percentiles from the latency histogram

### ISSUE THREAD

**Issue by mcollina** [nearform/anger#9]
cc @mtharrison

**Comment by mcollina** [comment]
Those are already present in `autocannon`: https://github.com/mcollina/autocannon/blob/master/lib/run.js#L234-L256, https://github.com/mcollina/autocannon/blob/master/lib/percentiles.js. We might even package up those functions from `autocannon` in an helper module.

**Comment by thekemkid** [comment]
https://github.com/thekemkid/hdr-histogram-precentiles-obj?

**Comment by thekemkid** [comment]
Uh, I'll fix that typo :P

**Comment by mcollina** [comment]
That can do :). Tests are missing, and docs too.

**Comment by thekemkid** [comment]
Added docs and tests, If you're cool with it I'll add a pr to use it

**Comment by mcollina** [comment]
`'use strict'` is missing. You can add some more relevant tests, and verify that _correct_ numbers are returned.

**Comment by thekemkid** [comment]
done
